# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89be3b811be433c237fe2142494b1dd667254952d9585412c81ae16edf863f2ed8d46a1989635cc37bea80d845fac11a5d6c7ac0a455bba01b9b32e65009cdd8

test:
  secret_key_base: cfca2f6bc0f9e4268a472e961c21b2c7abaa32eddcd6a62126279b2eb5e844ff0eca9c4f19340dd2e0c1e3c27a1b5eb0dbb539e1822bd77f1fb8789fcb727372

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
